int nf0(int x) pre(x > 0);
int nf0(int x);
int mf0(int x) pre(x > 0);
int nf1(int x) pre(x > 1);
int nf1(int x);
int mf1(int x) pre(x > 1);
int nf2(int x) pre(x > 2);
int nf2(int x);
int mf2(int x) pre(x > 2);
int nf3(int x) pre(x > 3);
int nf3(int x);
int mf3(int x) pre(x > 3);
int nf4(int x) pre(x > 4);
int nf4(int x);
int mf4(int x) pre(x > 4);
int nf5(int x) pre(x > 5);
int nf5(int x);
int mf5(int x) pre(x > 5);
int nf6(int x) pre(x > 6);
int nf6(int x);
int mf6(int x) pre(x > 6);
int nf7(int x) pre(x > 7);
int nf7(int x);
int mf7(int x) pre(x > 7);
int nf8(int x) pre(x > 8);
int nf8(int x);
int mf8(int x) pre(x > 8);
int nf9(int x) pre(x > 9);
int nf9(int x);
int mf9(int x) pre(x > 9);
int nf10(int x) pre(x > 10);
int nf10(int x);
int mf10(int x) pre(x > 10);
int nf11(int x) pre(x > 11);
int nf11(int x);
int mf11(int x) pre(x > 11);
